// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SoftballStats.Data;

#nullable disable

namespace SoftballStats.Migrations
{
    [DbContext(typeof(StatContext))]
    [Migration("20240705021721_PlayerModelFix2")]
    partial class PlayerModelFix2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SoftballStats.Models.GameStats", b =>
                {
                    b.Property<int>("StatsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatsID"));

                    b.Property<int?>("AtBats")
                        .HasColumnType("int");

                    b.Property<int?>("Doubles")
                        .HasColumnType("int");

                    b.Property<int?>("Errors")
                        .HasColumnType("int");

                    b.Property<DateTime>("GameDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GamesPlayed")
                        .HasColumnType("int");

                    b.Property<int?>("HitByPitch")
                        .HasColumnType("int");

                    b.Property<int?>("Hits")
                        .HasColumnType("int");

                    b.Property<int?>("HomeRuns")
                        .HasColumnType("int");

                    b.Property<string>("Opponent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PlayerID")
                        .HasColumnType("int");

                    b.Property<int?>("RBIs")
                        .HasColumnType("int");

                    b.Property<int?>("Runs")
                        .HasColumnType("int");

                    b.Property<int?>("SacrificeBunt")
                        .HasColumnType("int");

                    b.Property<int?>("SacrificeFly")
                        .HasColumnType("int");

                    b.Property<int?>("Singles")
                        .HasColumnType("int");

                    b.Property<int?>("StolenBases")
                        .HasColumnType("int");

                    b.Property<int?>("Strikeouts")
                        .HasColumnType("int");

                    b.Property<int?>("Triples")
                        .HasColumnType("int");

                    b.Property<int?>("Walks")
                        .HasColumnType("int");

                    b.HasKey("StatsID");

                    b.ToTable("Stats");
                });

            modelBuilder.Entity("SoftballStats.Models.Player", b =>
                {
                    b.Property<int>("PlayerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlayerID"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TeamID")
                        .HasColumnType("int");

                    b.HasKey("PlayerID");

                    b.HasIndex("TeamID");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("SoftballStats.Models.Team", b =>
                {
                    b.Property<int>("TeamID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeamID"));

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TeamID");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("SoftballStats.Models.Player", b =>
                {
                    b.HasOne("SoftballStats.Models.Team", "Team")
                        .WithMany("Players")
                        .HasForeignKey("TeamID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("SoftballStats.Models.Team", b =>
                {
                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
